### ISSUE TITLE
Phiền thầy

### ISSUE THREAD

**Issue by kurodenjiro** [trungtv/vivi_spacy#2]
Hiện tại em thấy file này bị lỗi thày update lại được không ạ 
https://github.com/trungtv/vivi_spacy/raw/master/vi/vi_core_news_md-2.0.1/dist/vi_core_news_md-2.0.1.tar.gz

**Comment by trungtv** [comment]
Chào em, 
Mình update lại readme, do github của mình hạn chế file lớn nên em có thể download từ google drive

**Comment by vietdien2005** [comment]
Hi anh, 
- Em đang thắc sao ko down dc thì thấy có phản hồi update Readme :smile: 
- Cái này anh có thể tạo tag và đẩy lên release cho tiện, không cần phải đẩy lên google drive :smile: 
- Với có thể cho em xin tài liệu build được ko anh nhỉ

**Comment by trungtv** [comment]
Tài liệu build em tham khảo trực tiếp trên trang của spacy em nhé. Trên đó là chuẩn nhất.
