### ISSUE TITLE
Chạy lệnh cp vi/vi  như thế nào mới đúng

### ISSUE THREAD

**Issue by phuchung15** [trungtv/vivi_spacy#5]
Chào Anh !
Em chạy lệnh cp vi/vi C:\Users\Lam\Anaconda3\Lib\site-packages\spacy\lang\vi
Nhưng hiện thông báo là
cp : Cannot find path 'D:\project\python\training\vi\vi' because it does not exist.
Em vào thư mục nào để chạy dc lênh trên

**Comment by trungtv** [comment]
Thư mục vi/vi này là thư mục clone từ github về. Lưu ý model này mình build hiện tại ko work với spacy version >= 2.1.

**Comment by phuchung15** [comment]
Cảm ơn Anh !
Hiên tại em đang chay spacy 2.1.4 nên ko chạy dc nữa.
