### ISSUE TITLE
spaCy version 

### ISSUE THREAD

**Issue by nqnhan1403** [trungtv/vivi_spacy#6]
Hi @trungtv ,

At first many thanks for your contribution.

when using spaCy version 2.1.4, I loaded model successfully. However, it can't recognize tagger and pos (pos alway is "X" letter and tag is something I do not understand) and entity is blank for every word, then I saw your information, i know that must use spaCy versions < 2.1.0. But I try to install spaCy 1.9.0 i get error about: **_cl.exe' failed with exit status 2_**, then I moving to version 2.0.11, I install it successful, but I can not load model because this error: **_ValueError: could not broadcast input array from shape (96) into shape (128)_**. 

**Could you please provide a specific of spaCy version which working fine with your project or maybe some advice to solve my problem**

Thank you
Nhan Nguyen

**Comment by trungtv** [comment]
Dear Nhan, 
Thanks for trying out. Vivi_Spacy does not contain POS and NER tag as it is trained on UD_Vietnamese_VTB dataset (only Tag and Dep are available). I am planing to update the model by today so you can run the latest version of Spacy.IO
Bests

**Comment by trungtv** [comment]
Hello, 
vivi_spacy is outdated. Let's move to https://github.com/trungtv/vi_spacy
